def test_failure():
    raise AssertionError('Oh no..')
